version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  assignees:
    - marekdedic
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
  assignees:
    - marekdedic
